const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const quotes={motivasi:["Hari ini mungkin berat, tetapi kamu tidak harus berhenti.","Pelan bukan berarti gagal. Yang penting, kamu tetap bergerak.","Tidak harus sempurna untuk memulai. Mulailah, lalu bertumbuh.","Satu langkah kecil hari ini tetap membawa kamu lebih dekat."],islami:["Jaga niat, rapikan ikhtiar, lalu serahkan hasil kepada Allah.","Saat hati lelah, berhenti sejenak untuk mengingat bahwa Allah selalu dekat.","Tidak semua jawaban datang cepat. Tetap berdoa, berusaha, dan bersabar.","Semoga langkah kecilmu menjadi jalan menuju keberkahan."],mutiara:["Tidak semua proses harus terlihat untuk menjadi berarti.","Yang tenang bukan berarti tanpa masalah; ia hanya belajar tidak menyerah pada keadaan.","Jadilah alasan seseorang kembali percaya pada kebaikan.","Waktu mengajarkan: yang tulus tidak selalu ramai, tetapi sering kali paling berarti."],belajar:["Belajar satu halaman hari ini lebih baik daripada menunggu sempurna.","Kalau sulit, pecah menjadi kecil. Kalau lelah, istirahat. Jangan menyerah.","Tidak perlu mengalahkan siapa pun. Cukup kalahkan rasa ingin berhenti.","Konsisten 30 menit setiap hari bisa mengubah kemampuanmu."]};
const palettes={obsidian:{a:"#e1c98d",b:"#a9c4ae",bg1:"#0b1610",bg2:"#1a2c21"},desert:{a:"#f0d7a0",b:"#e7d8bc",bg1:"#33281d",bg2:"#765e43"},evergreen:{a:"#d6d995",b:"#b9d4bc",bg1:"#082018",bg2:"#1e5039"},plum:{a:"#e6b9c9",b:"#d7bec8",bg1:"#25161f",bg2:"#5b3447"}};
let category="motivasi",theme="obsidian",aiImage=null;const canvas=$("#canvas"),ctx=canvas.getContext("2d");
function setRatio(){const s={square:[1080,1080],portrait:[1080,1350],story:[1080,1920]}[$("#ratio").value];[canvas.width,canvas.height]=s;draw()}
function wrap(t,max){const lines=[];let line="";for(const w of t.trim().split(/\s+/)){const x=line?line+" "+w:w;if(ctx.measureText(x).width>max&&line){lines.push(line);line=w}else line=x}if(line)lines.push(line);return lines}
function draw(){const w=canvas.width,h=canvas.height,p=palettes[theme];let g=ctx.createLinearGradient(0,0,w,h);g.addColorStop(0,p.bg1);g.addColorStop(1,p.bg2);ctx.fillStyle=g;ctx.fillRect(0,0,w,h);if(aiImage){ctx.save();ctx.globalAlpha=.8;ctx.drawImage(aiImage,0,0,w,h);ctx.restore()}let glow=ctx.createRadialGradient(w*.76,h*.14,10,w*.76,h*.14,w*.62);glow.addColorStop(0,p.a+"45");glow.addColorStop(1,"transparent");ctx.fillStyle=glow;ctx.fillRect(0,0,w,h);ctx.strokeStyle=p.a+"50";ctx.lineWidth=2;ctx.beginPath();ctx.arc(w/2,h/2,Math.min(w,h)*.36,0,Math.PI*2);ctx.stroke();ctx.textAlign="center";ctx.fillStyle=p.a;ctx.font="700 "+Math.max(22,w*.023)+"px DM Sans";ctx.fillText(category==="islami"?"☾  RENUNGAN":"✦  "+category.toUpperCase(),w/2,h*.16);const text=$("#quote").value.trim()||quotes[category][0],size=category==="islami"?Math.max(42,w*.052):Math.max(40,w*.05);ctx.font="600 "+size+"px DM Sans";const lines=wrap(text,w*.78),lh=size*1.22;let y=(h-lh*lines.length)/2;ctx.fillStyle="#f7f5ee";for(const line of lines){ctx.fillText(line,w/2,y);y+=lh}ctx.fillStyle=p.b;ctx.font="500 "+Math.max(19,w*.019)+"px DM Sans";ctx.fillText("NurMotivasi Studio",w/2,h*.86);ctx.fillStyle=p.a+"aa";ctx.font="700 "+Math.max(12,w*.012)+"px DM Sans";ctx.fillText("BUAT BAIK  •  BAGIKAN BAIK",w/2,h*.9)}
function useQuote(q){$("#quote").value=q;draw()}
$("#category").onchange=e=>{category=e.target.value;$("#quote").value=quotes[category][0];draw()};
$("#quote").oninput=draw;$("#ratio").onchange=setRatio;
$$(".swatch").forEach(b=>b.onclick=()=>{$$(".swatch").forEach(x=>x.classList.remove("active"));b.classList.add("active");theme=b.dataset.theme;draw()});
$$(".chips button").forEach(b=>b.onclick=()=>useQuote(b.dataset.quote));
$("#generate").onclick=()=>{$("#status").textContent="Composition rendered ✓";draw()};
$("#random").onclick=()=>{useQuote(quotes[category][Math.floor(Math.random()*quotes[category].length)]);$("#status").textContent="New inspiration ✦"};
$("#copy").onclick=async()=>{try{await navigator.clipboard.writeText($("#quote").value);$("#status").textContent="Quote copied ✓"}catch{$("#status").textContent="Copy manual diperlukan"}};
$("#download").onclick=()=>{draw();const a=document.createElement("a");a.download="nurmotivasi-"+category+".png";a.href=canvas.toDataURL("image/png");a.click();$("#status").textContent="PNG downloaded ✓"};
$("#aiGenerate").onclick=async()=>{const prompt=$("#aiPrompt").value.trim();if(!prompt){$("#status").textContent="Isi prompt AI dulu";return}const endpoint=window.NURMOTIVASI_AI_ENDPOINT||"/api/generate-image";$("#aiGenerate").disabled=true;$("#aiGenerate").textContent="Generating…";$("#status").textContent="AI sedang bekerja…";try{const r=await fetch(endpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({prompt,size:$("#ratio").value==="story"?"1024x1536":"1024x1024"})});const d=await r.json();if(!r.ok)throw new Error(d.error||"AI endpoint tidak tersedia");const img=new Image();img.onload=()=>{aiImage=img;draw();$("#status").textContent="AI background siap ✓"};img.src=d.image}catch(e){$("#status").textContent="AI belum aktif di GitHub Pages";$("#aiHint").textContent=e.message+" Gunakan serverless endpoint untuk mengaktifkannya."}finally{$("#aiGenerate").disabled=false;$("#aiGenerate").innerHTML='Generate background <span>↗</span>'}};
$("#quote").value=quotes[category][0];setRatio();